### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Arduino0923** [Th30neAnd0nly/Ohm#1]
Could you create a tutorial on how to create the project please

**Comment by graysuit** [comment]
https://github.com/Th30neAnd0nly/Ohm#how-to-use
read/do step by step

**Comment by Arduino0923** [comment]
> https://github.com/Th30neAnd0nly/Ohm#how-to-use
> read/do step by step

do all the steps but it doesn't work for me please help

**Comment by prateek-chaubey** [comment]
On which step you are getting problem

**Comment by prateek-chaubey** [comment]
> > https://github.com/Th30neAnd0nly/Ohm#how-to-use
> > read/do step by step
> 
> do all the steps but it doesn't work for me please help

As you are not replying to this issue , so  I am closing this issue you can further discuss your problems at https://discord.gg/fsDrvdYswP
