### ISSUE TITLE
web penal

### ISSUE THREAD

**Issue by lucifer5207** [Th30neAnd0nly/Ohm#15]
Hello Sir, you did a very great job... but i have some issues related to the web penal... i follow your steps build insta mod apk and install it and first of all its detectable by antivirus (photo no.1).... when i logged in with my insta account then credentials are captured and shown in the firebase account... i paste the web app config details in app.js and save it (photo no.2) but app.js is not running (photo no.3)... i want to use other features of this amazing RAT for that i need your help to develop that command base web penal... hosting error too (photo no.4).... pleaseeee help @prateek-chaubey
![IMG_20220202_205427](https://user-images.githubusercontent.com/98893212/152184534-3d36d199-b844-4e6f-a68c-14036ef4e19c.jpg)
![IMG_20220202_205333](https://user-images.githubusercontent.com/98893212/152184602-a71a6813-7e63-467d-b3ac-bb07d8b1b27f.jpg)
![IMG_20220202_205406](https://user-images.githubusercontent.com/98893212/152184636-82b27d1a-7666-49f6-a8f9-fd11017ff23d.jpg)
![IMG_20220202_205504](https://user-images.githubusercontent.com/98893212/152184666-3e05a429-a584-4586-a217-78ec325c9cf3.jpg)

**Comment by tweakvile** [comment]
Run some intercepting cmd

**Comment by lucifer5207** [comment]
> Run some intercepting cmd

intercepting cmd like ?

**Comment by prateek-chaubey** [comment]
1. When any project is made open source , it becomes detectable by antiviruses.
2. This is not `node.js` project , you have can either host it on your localhost or any hosting provider.

**Comment by lucifer5207** [comment]
> 

Can you make tutorial on this and send me?

**Comment by prateek-chaubey** [comment]
Already Mentioned in Readme

**Comment by lucifer5207** [comment]
> Already Mentioned in Readme

sir i already tried and follow your steps.... i just need to open that web penal so i can use other features of your R.A.T. too... i generate apk from sketchware and login to my account and credentials are captured by firebase... but i want to use web penal too

**Comment by lucifer5207** [comment]
> Already Mentioned in Readme

what commands i have to run in my linux machine to run that web penal??

**Comment by prateek-chaubey** [comment]
You have to host it on localhost.

**Comment by lucifer5207** [comment]
> You have to host it on localhost.

you mean i have to execute index html with google chrome (google-chrome index html) for web penal?

**Comment by lucifer5207** [comment]
sir i put web penal files in the 000webhost... and it works... but when i put the command it says you are not the admin
![IMG_20220205_170917](https://user-images.githubusercontent.com/98893212/152640605-c8174f98-22e2-4ece-b642-6f756810198d.jpg)

**Comment by prateek-chaubey** [comment]
Because there aren't any online victim devices.
Install the app and then click on the user id ,  then it will establish connection with that specific device.

**Comment by lucifer5207** [comment]
i already installed the apk... and in realtime database it shows online (photo no 1)
but in the ohm web penal it's not showing any online devices
![1](https://user-images.githubusercontent.com/98893212/152675480-372f9af5-55ac-45d8-b334-c76a2d11ca61.jpg)
![2](https://user-images.githubusercontent.com/98893212/152675495-de34557d-c801-4000-8f54-aab5f4b00ecf.jpg)
![3](https://user-images.githubusercontent.com/98893212/152675503-ed1990f6-ed2d-4a3c-9249-6e21d569b2f3.jpg)
![4](https://user-images.githubusercontent.com/98893212/152675509-003ad487-b654-4366-92de-78185d3ae0c3.jpg)

even i copied the UID from authentication logs but it says you are admin cannot apply commads
only "CLEAR" COMMAD AND "HELP" COMMAD ARE WORKING

**Comment by lucifer5207** [comment]
thank you so much for your help... now its working.... i tested on my phone is working great.... thanks again for support
