### ISSUE TITLE
why name nikola_tesla in instagram mod?

### ISSUE THREAD

**Issue by vokica** [Th30neAnd0nly/Ohm#19]
why is it called nikola_tesla?

**Comment by Tweakvile** [comment]
Package name can be anything

**Comment by Tweakvile** [comment]
That's is the package name

**Comment by vokica** [comment]
im asking why nikola tesla why that name

**Comment by prateek-chaubey** [comment]
It's my choice , it can name it anything. Even you can rename it to anything you want.

**Comment by Tweakvile** [comment]
That's the package name
