### ISSUE TITLE
Please upload a video showing how to build the application please

### ISSUE THREAD

**Issue by Arduino0923** [Th30neAnd0nly/Ohm#2]
Please upload a video showing how to build the application please

**Comment by Arduino0923** [comment]
help me please

**Comment by prateek-chaubey** [comment]
So can you tell on which step you are getting problem.

**Comment by Arduino0923** [comment]
> So can you tell on which step you are getting problem.

I can't make the connection with firebase please can you create a video of how to create the apk and the connection with the server please

**Comment by prateek-chaubey** [comment]
> > So can you tell on which step you are getting problem.
> 
> I can't make the connection with firebase please can you create a video of how to create the apk and the connection with the server please

Just you need is the ``` google-services.json ``` file , which contains all the data about your Firebase including API Key , Storage Bucket URL , etc.

Then Fill all the information in Sketchware Pro app's Firebase Section , that's all.

**Comment by Arduino0923** [comment]
> > > So can you tell on which step you are getting problem.
> > 
> > 
> > I can't make the connection with firebase please can you create a video of how to create the apk and the connection with the server please
> 
> Just you need is the `google-services.json` file , which contains all the data about your Firebase including API Key , Storage Bucket URL , etc.
> 
> Then Fill all the information in Sketchware Pro app's Firebase Section , that's all.

I have followed this process, but it does not work for me please could you create a video of how to create the apk and make the connection to the server please
send me your telegram to consult you please

**Comment by prateek-chaubey** [comment]
Here is [Discord Server Link](https://discord.gg/fsDrvdYswP) you can contact me There.
