### ISSUE TITLE
did not find instagram mod.swb 

### ISSUE THREAD

**Issue by bytesmalware** [Th30neAnd0nly/Ohm#20]
...

**Comment by Tweakvile** [comment]
Do you need it

**Comment by bytesmalware** [comment]
yess

**Comment by bytesmalware** [comment]
> 

i want sketchware which do not crash in my system

**Comment by Tweakvile** [comment]
Chat me up on telegram @Tweakville

**Comment by bytesmalware** [comment]
![Screenshot_20220321-043300.png](https://user-images.githubusercontent.com/65878389/159189948-b95c2b8e-c215-4091-886e-800781dd292b.png)

**Comment by bytesmalware** [comment]
Error comes while signing the app , i tried many times , yet failed each time

**Comment by Tweakvile** [comment]
No problem I got it
Chat me up on telegram @Tweakville
