### ISSUE TITLE
Error in exicuting the index file i don't know what happend

### ISSUE THREAD

**Issue by KARTIKSORMARE** [Th30neAnd0nly/Ohm#24]
Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).

Showing this error

**Comment by KARTIKSORMARE** [comment]
https://user-images.githubusercontent.com/68058195/173098145-00c1a1e1-7bd3-40fb-922c-9b3c5d2a804d.mp4

This is the error i am getting

**Comment by KARTIKSORMARE** [comment]
@prateek-chaubey please 🥺 solve this issue what should I do ??..

**Comment by prateek-chaubey** [comment]
In your `app.js` file 
add this line `firebase.initializeApp(firebaseConfig);
`

**Comment by KARTIKSORMARE** [comment]
@prateek-chaubey  This is done thanks👍👍🙏
