### ISSUE TITLE
Cannt connect to firebase

### ISSUE THREAD

**Issue by BlackStack7** [Th30neAnd0nly/Ohm#25]
I did'nt understan, i follow the step and your realtime database look like this.
![image](https://user-images.githubusercontent.com/103115026/173620188-2e81f24e-5f79-462f-80f4-49397ea00c51.png)

and mine like this:
![image](https://user-images.githubusercontent.com/103115026/173620278-05ba4c42-dcc0-408f-ab2d-6c0f1e349e37.png)

can you help me?

**Comment by prateek-chaubey** [comment]
You have to add these data nodes manually as shown in the image.

**Comment by BlackStack7** [comment]
have made it manually :
![image](https://user-images.githubusercontent.com/103115026/173722938-c49482b4-4d39-44a0-90f4-4e4ec214a0bc.png)

but i can only do help and clear command
