### ISSUE TITLE
command not working 

### ISSUE THREAD

**Issue by duruik123** [Th30neAnd0nly/Ohm#29]
whenever i type a command i get this response
$ admin#~   You Are Admin. Cannot Apply Command.

**Comment by prateek-chaubey** [comment]
After successful installation of rat in victim's device it will show a unique id on the web panel.
Click on that unique id to connect to victim , afterwards you can run all the commands.

**Comment by duruik123** [comment]
please can you show me a video tutorial or some screenshot because i have follow all the instruction still not yet working
after installing the app on my own phone to test it still not working
