### ISSUE TITLE
Invalid to number block ""

### ISSUE THREAD

**Issue by mountaincastle47** [Th30neAnd0nly/Ohm#30]
App doesn't open

**Comment by prateek-chaubey** [comment]
Follow the steps again , seems like you haven't followed the step 5.

**Comment by mountaincastle47** [comment]
Do i need a subscription for firebase for that

**Comment by prateek-chaubey** [comment]
No you don't need any kind of subscription.
Follow the video tutorial given below in the readme section, you will get to know how to do that.

**Comment by mountaincastle47** [comment]
![Screenshot_20220905-155304](https://user-images.githubusercontent.com/66811246/188383476-2bc25401-a166-497e-95de-04611330c506.png)
I did as the video

**Comment by mountaincastle47** [comment]
Can you give me a json file for the database

**Comment by prateek-chaubey** [comment]
Watch the videos given on `ReadMe` file.

https://github.com/Th30neAnd0nly/Ohm#tutorial-video

**Comment by mountaincastle47** [comment]
> Watch the videos given on `ReadMe` file.
> 
> https://github.com/Th30neAnd0nly/Ohm#tutorial-video

Doesn't show how to setup database

**Comment by prateek-chaubey** [comment]
> > Watch the videos given on `ReadMe` file.
> > https://github.com/Th30neAnd0nly/Ohm#tutorial-video
> 
> Doesn't show how to setup database

Seems like you haven't watched the video at all.
Dude watch the video , all the solutions are given there.

**Comment by mountaincastle47** [comment]
> > > Watch the videos given on `ReadMe` file.
> > > https://github.com/Th30neAnd0nly/Ohm#tutorial-video
> > 
> > 
> > Doesn't show how to setup database
> 
> Seems like you haven't watched the video at all. Dude watch the video , all the solutions are given there.

I watched and there is no part of it making the json file to import to real time database

**Comment by mountaincastle47** [comment]
Nvm i made the json myself now it works

**Comment by prateek-chaubey** [comment]
Dude I literally posted the tutorial video containing all the steps, and you are saying that there isn't any step regarding that.
Think 1000 times before giving any baseless conclusion.

**Comment by mountaincastle47** [comment]
> Dude I literally posted the tutorial video containing all the steps, and you are saying that there isn't any step regarding that. Think 1000 times before giving any baseless conclusion.

I mean step 5 where you have to manually make a json file to make ot look like the image
