### ISSUE TITLE
Issue while opening Sketchware Pro. 

### ISSUE THREAD

**Issue by MisirAli963** [Th30neAnd0nly/Ohm#31]
I am having an issue while I open Sketchware Pro. It throws an error which I have attached below. This is why I can't build the app as well. 
![Screenshot_98](https://user-images.githubusercontent.com/114070554/191486752-4f055120-9cd1-4240-9681-50042368a6a9.png)

**Comment by prateek-chaubey** [comment]
There isn't any problem with the Sketchware Pro.
This is an internal error of Sketchware there won't be any effect on RAT while building it.

**Comment by MisirAli963** [comment]
Can not build the app. Throws an error 
![Screenshot_99](https://user-images.githubusercontent.com/114070554/191488038-88896ac6-2284-4223-a148-13161c4f185d.png)

**Comment by prateek-chaubey** [comment]
Which version of Sketchware Pro are you using?

**Comment by MisirAli963** [comment]
I've downloaded this today. 

![image](https://user-images.githubusercontent.com/114070554/191489503-923ffb43-45d9-4c34-8567-1c94a70f9f5d.png)

**Comment by prateek-chaubey** [comment]
Try uninstalling the app and restoring the project again.

**Comment by MisirAli963** [comment]
Okay. Thank you. Will get back here if doesn't work

**Comment by MisirAli963** [comment]
Reinstalled and tried. Same issue.

**Comment by MisirAli963** [comment]
Is there any android version requirement or any particular device requirements?? I'm using Emulator

**Comment by prateek-chaubey** [comment]
Sketchware may not work properly in emulators, use an actual android device.
