### ISSUE TITLE
Upload file lag and where to get it from

### ISSUE THREAD

**Issue by Guru-2007** [Th30neAnd0nly/Ohm#35]

**Comment by Guru-2007** [comment]
Uploadfile command got lag and no file came to my firebase storage,Where do I get it

**Comment by prateek-chaubey** [comment]
Have you enabled firebase storage?

**Comment by Guru-2007** [comment]
Yes air I had done But as soon as I ecexute upload file command it pop up some errors and end application option coming from the mod

**Comment by Guru-2007** [comment]
![Screenshot_20230603-225149](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/9e1da138-df5b-4645-851b-3027f3a4dba1)
![Screenshot_20230603-225158](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/c08ba90b-2dc2-4cf8-aab1-b17273d05f5f)
![Screenshot_20230603-225206](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/0083ed7c-0641-4bd7-96f6-ef2890a369f2)
![Screenshot_20230603-225305](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/bdbc866f-8161-4c55-bddc-4034b704110e)
![Screenshot_20230603-225313](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/32438a43-8a5a-4233-839d-595ce73df05f)
![Screenshot_20230603-225321](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/d633b7f9-1e4d-4c75-9799-63ef81baf534)

**Comment by Guru-2007** [comment]
This popping out

**Comment by prateek-chaubey** [comment]
Can you send me the screenshot of Firebase Storage rules section

**Comment by Guru-2007** [comment]
![Uploading Screenshot_20230604-080849.png…]()

**Comment by Guru-2007** [comment]
![Uploading Screenshot_20230604-080849.png…]()

**Comment by Guru-2007** [comment]
![Screenshot_20230604-080849](https://github.com/Th30neAnd0nly/Ohm/assets/135450624/3f6ad051-7153-428c-8174-e3602b50ac5e)

**Comment by Guru-2007** [comment]
Sir the issue got resolved, You are literally GOD to create such easy operated undetectable free Service. At last I just want to know would I also access camera or microphone through this

**Comment by prateek-chaubey** [comment]
Try [AIRAVAT](https://github.com/Th30neAnd0nly/AIRAVAT)
