### ISSUE TITLE
App Data not connecting

### ISSUE THREAD

**Issue by fdavids77** [Th30neAnd0nly/Ohm#6]
not getting any connection from the android phone after installing the app, i can see test data in the web console comming from the firebase database but nothing from the phone

**Comment by prateek-chaubey** [comment]
If the Connection between Firebase and app is correct then there may be problem in your web panel. Have you pasted the config correctly.

**Comment by fdavids77** [comment]
The problem seems to be between the app and firebase, as i can pull the test data from firebase to the webpanel on my server

**Comment by prateek-chaubey** [comment]
Is there any error after opening the app.and make sure that you have configured the Firebase correctly in the ap.

**Comment by Sagar-990** [comment]
@fdavids77 hey, let's talk on whatsapp and create this RAT together. I also need help from you. I've not tried creating a rat before.

**Comment by Sagar-990** [comment]
@prateek-chaubey which project overview and android app are you talking about in your steps?

**Comment by prateek-chaubey** [comment]
@Sagar-990  Read all the steps carefully , you will get to know.

**Comment by Sagar-990** [comment]
@prateek-chaubey and why did you deleted my comment when i told @fdavids77 to collaborate with me?

**Comment by prateek-chaubey** [comment]
@Sagar-990  You can contact @fdavids77  from social media , here only we discuss the issues.

**Comment by Sagar-990** [comment]
@prateek-chaubey how do i know his social media?

**Comment by prateek-chaubey** [comment]
Even when you have tagged him he received a mail notification. So , whenever he will see the mail he will contact you.

**Comment by Sagar-990** [comment]
@prateek-chaubey and why is tutorial so expensive?

**Comment by prateek-chaubey** [comment]
I don't think so.
