### ISSUE TITLE
HAVE CONTACT?

### ISSUE THREAD

**Issue by donaldhit** [Th30neAnd0nly/Ohm#9]
HI BROTHER HAVE EMAIL FROM CONTACT? I LIKE YOUR SCRIPT

**Comment by prateek-chaubey** [comment]
If you want to contact me you can join our Discord Server.
 [![Join our Discord server!](https://invidget.switchblade.xyz/8DsczzxU9E)](http://discord.gg/8DsczzxU9E)

**Comment by krisdowis** [comment]
> If you want to contact me you can join our Discord Server.
>  [![Join our Discord server!](https://invidget.switchblade.xyz/8DsczzxU9E)](http://discord.gg/8DsczzxU9E)
> 

Invite link expired

**Comment by prateek-chaubey** [comment]
Contact me through [Telegram](https://t.me/th30neand0nly)
